"""add extracted text to resumes

Revision ID: f230fb7f72c0
Revises: 2764933424e4
Create Date: 2026-08-22 10:52:52.706255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f230fb7f72c0'
down_revision: Union[str, Sequence[str], None] = '2764933424e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'extracted_text')
    # ### end Alembic commands ###
